### ISSUE TITLE
Uncaught TypeError: Cannot set property 'Constructor' of undefined on v4.0.1 when jQuery present

### ISSUE THREAD

**Issue by kdhana** [coreui/coreui#245]
Please, don't close this issue as a duplicate of #235 before reading the following.

`Uncaught TypeError: Cannot set property 'Constructor' of undefined at coreui.esm.js:312`

I am using version 4.0.1 with jQuery 3.6.0 present (jQuery is a project dependency, obviously unrelated to CoreUI v4). 

CoreUI tries to detect jQuery presence, and throws this error if jQuery is indeed present.

**Comment by cocowalla** [comment]
I'm using `coreui.bundle.js`, but get a similar error when jQuery is included, which presumably is related to your error:

`Uncaught TypeError: can't access property "Constructor", $.fn[name] is undefined`

I've tracked it down to [here, in `defineJQueryPlugin`](https://github.com/coreui/coreui/blob/8e84bd5bd12f0ddcd55c4cce06c848a26e0625a8/js/src/util/index.js#L234), and AFAIKS the issue is a simple typo, where `$.fn[name].Constructor = plugin` should be `$.fn[name].constructor = plugin` (note the lower-case 'c'!)

**Comment by kdhana** [comment]
> I'm using coreui.bundle.js, but get a similar error when jQuery is included, which presumably is related to your error:

Yes, it is.

**Comment by cocowalla** [comment]
Actually, did some more digging and it's not only that typo, there are issues in the `Sidebar` and `Navigation` classes too - I'll submit a PR.

**Comment by vaibhav3027** [comment]
This error is also preventing tooltip from showing up.

**Comment by cocowalla** [comment]
@mrholek is it possible to get this merged when you have time? Thanks! 🙏

**Comment by vaibhav3027** [comment]
@mrholek <https://github.com/mrholek> This is a daily reminder on this
issue.

**Comment by vaibhav3027** [comment]
@mrholek This is a daily reminder on this issue.

**Comment by cocowalla** [comment]
@vaibhav3027 mate, I want this merged too, but spamming like this is **_not_** the way - it's rude and disrepectful of an OSS maintainer's time. Please stop.

**Comment by mrholek** [comment]
Fixed
