### ISSUE TITLE
Sidebar not hide when click outside on mobile

### ISSUE THREAD

**Issue by duyld2108** [coreui/coreui#254]
Sidebar toggle can show on mobile device but can not close when click outside of sidebar (eg. backdrop or body).

It seem maybe document not listen event after show.

**Comment by TheseGoTo11** [comment]
I have this issue too, using CoreUI 4.1.0. Toggling the sidebar by doing
`coreui.Sidebar.getInstance(document.querySelector(‘#sidebar’)).toggle()`
will show the sidebar, and create the sidebar-backdrop div element. On Windows/Chrome, clicking on the backdrop element instead of the sidebar will hide the sidebar as expected. But on Safari/iOS 4.1.0, nothing happens.

**Comment by mrholek** [comment]
Fixed in v4.1.1
