### ISSUE TITLE
Scss variable $header-min-height not respected (migration to v5)

### ISSUE THREAD

**Issue by meriturva** [coreui/coreui#750]
See here:

https://github.com/coreui/coreui/blob/e4cafcfbe8a081f9c20a5e647a7ab24616ef3d68/scss/_header.scss#L36

any reason for that?
Thanks.

**Comment by meriturva** [comment]
Any news @mrholek ? I didn't see any changes related to that and other scss issues on last week's release (v5.0.1).
So thanks.

**Comment by mrholek** [comment]
We removed `$header-min-height` and `$sidebar-brand-height` because the main purpose was to have the height of template elements the same. As it is more relevant to templates, not library, we decided to move those styles here - https://github.com/coreui/coreui-free-bootstrap-admin-template/blob/main/src/scss/_theme.scss

**Comment by meriturva** [comment]
Thanks, customization created on my theme files!
