### ISSUE TITLE
Selector.NAV_LINK_QUERIED must be "nav-link-queried"

### ISSUE THREAD

**Issue by expressiveco** [coreui/coreui#83]
Class names in `Element.classList `do not include dots. So, `Selector.NAV_LINK_QUERIED `must be `"nav-link-queried"`.

https://github.com/coreui/coreui/blob/97d3bbde24bb554f77d32583717737789e8c21d0/js/src/sidebar.js#L57

**Comment by xidedix** [comment]
@expressiveco 
Thanks for the heads-up!

**Comment by gtruini** [comment]
anyway we can get this fixed in setActiveLink? Not use the "." when searching the class list. This is causing some painful UX that we can't get around now that we've added selenium tests. Selenium tests do not like class="nav-link .nav-link-queried"...although this incorrect syntax did fix our issue otherwise.

**Comment by xidedix** [comment]
Hi @expressiveco @gtruini 

please update to `^2.1.15` and let us know if it works for you
